name: Version Tracking

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  run-version-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Npgsql
        run: dotnet add package Npgsql

      - name: Run version tracking script
        env:
          PG_CONNECTION_STRING: ${{ secrets.PG_CONNECTION_STRING }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet run --project ./ConsoleApp1
